### PR TITLE
Correcting API endpoints for operations on API models. Current end-po…

### PR DESCRIPTION
**Pull request by vivekwassan**
…ints are giving http 404 response

### CODE REVIEW

**Comment by giteshk** [comment]
@vivekwassan What is the endpoint that you have configured for your service?
It should be smartdocs/apis
Also the resource name should be empty and that defaults to smartdocs.

**Comment by ssvaidyanathan** [comment]
@giteshk - Can we close this issue as its not required ?

**Comment by giteshk** [comment]
Yes lets close this thanks @ssvaidyanathan for taking care of this with the @vivekwassan

**Comment by ssvaidyanathan** [comment]
Thanks @giteshk - closing this as its not an issue anymore

**Pull request closed without merging**
